---
- name: Crear Disco
  hosts: localhost

  vars:
    gcp_project: proyecto
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ./proyecto-serviceacount.json
    zone: "europe-west6-a"
    region: "europe-west6"
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:
    - name: Creando...
      gcp_compute_disk:
        name: 'disk-instance'
        size_gb: 10
        source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts'
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes: "{{ scopes }}"
        state: present
      register: disk

