---
- name: Gestionar Infraestructura
  hosts: localhost

  vars_prompt:
    - name: accion
      prompt: "Acción (present/absent)? "
      private: no

  vars:
    gcp_project: proyecto
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ./proyecto-serviceaccount.json
    zone: "europe-west6-a"
    region: "europe-west6"
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:
    - name: Creando Disco
      gcp_compute_disk:
        name: 'disk-instance'
        size_gb: 10
        source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts'
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes: "{{ scopes }}"
        state: "{{accion}}"
      when: accion == "present"
      register: disk
      
    - name: Creando Instancia
      gcp_compute_instance:
        name: "instance-test"
        machine_type: n1-standard-1
        disks:
        - auto_delete: true
          boot: true
          source: "{{ disk }}"
        network_interfaces:
        - network:
            selflink: "default"
          access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: "{{accion}}"
      register: instance
